baseURL = "https://gouten5010.github.io/hugo-blog/"
publishDir = "docs"
canonifyurls = true

languageCode = "ja"
title = "Hugo Demo"
theme="archie"
copyright = "© DOT LiNE SQUARE"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

HasCJKLanguage = true

paginate=3 # articles per page

[params]
	mode="light" # color-mode → light,dark or auto
	featherIconsCDN=true
	subtitle = "This is Hugo demo site."

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/gouten5010/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://github.com/gouten5010"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Notes"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4